# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magcil_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='magcil_api.proto',
  package='magcilapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10magcil_api.proto\x12\tmagcilapi\"t\n\x0c\x41udioRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\n\n\x02\x66s\x18\x04 \x01(\x05\x12\x0e\n\x06models\x18\x05 \x03(\t\x12\x15\n\rmodel_version\x18\x06 \x01(\t\"\x9a\x01\n\x0bMagCilReply\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12(\n\x05preds\x18\x02 \x03(\x0b\x32\x19.magcilapi.Preds_per_file\x12-\n\x07\x63lasses\x18\x03 \x03(\x0b\x32\x1c.magcilapi.Classes_per_model\x12\x0c\n\x04step\x18\x04 \x03(\x05\x12\x12\n\nmodel_name\x18\x05 \x03(\t\"\x1b\n\x0ePreds_per_file\x12\t\n\x01p\x18\x01 \x03(\x05\"\x1f\n\x11\x43lasses_per_model\x12\n\n\x02\x63l\x18\x01 \x03(\t2V\n\x12\x41udioModelsPredict\x12@\n\x07Predict\x12\x17.magcilapi.AudioRequest\x1a\x16.magcilapi.MagCilReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_AUDIOREQUEST = _descriptor.Descriptor(
  name='AudioRequest',
  full_name='magcilapi.AudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='magcilapi.AudioRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='magcilapi.AudioRequest.dimension', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='magcilapi.AudioRequest.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fs', full_name='magcilapi.AudioRequest.fs', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models', full_name='magcilapi.AudioRequest.models', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_version', full_name='magcilapi.AudioRequest.model_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=147,
)


_MAGCILREPLY = _descriptor.Descriptor(
  name='MagCilReply',
  full_name='magcilapi.MagCilReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='magcilapi.MagCilReply.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preds', full_name='magcilapi.MagCilReply.preds', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classes', full_name='magcilapi.MagCilReply.classes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='magcilapi.MagCilReply.step', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='magcilapi.MagCilReply.model_name', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=304,
)


_PREDS_PER_FILE = _descriptor.Descriptor(
  name='Preds_per_file',
  full_name='magcilapi.Preds_per_file',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='magcilapi.Preds_per_file.p', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=333,
)


_CLASSES_PER_MODEL = _descriptor.Descriptor(
  name='Classes_per_model',
  full_name='magcilapi.Classes_per_model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cl', full_name='magcilapi.Classes_per_model.cl', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=366,
)

_MAGCILREPLY.fields_by_name['preds'].message_type = _PREDS_PER_FILE
_MAGCILREPLY.fields_by_name['classes'].message_type = _CLASSES_PER_MODEL
DESCRIPTOR.message_types_by_name['AudioRequest'] = _AUDIOREQUEST
DESCRIPTOR.message_types_by_name['MagCilReply'] = _MAGCILREPLY
DESCRIPTOR.message_types_by_name['Preds_per_file'] = _PREDS_PER_FILE
DESCRIPTOR.message_types_by_name['Classes_per_model'] = _CLASSES_PER_MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioRequest = _reflection.GeneratedProtocolMessageType('AudioRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOREQUEST,
  '__module__' : 'magcil_api_pb2'
  # @@protoc_insertion_point(class_scope:magcilapi.AudioRequest)
  })
_sym_db.RegisterMessage(AudioRequest)

MagCilReply = _reflection.GeneratedProtocolMessageType('MagCilReply', (_message.Message,), {
  'DESCRIPTOR' : _MAGCILREPLY,
  '__module__' : 'magcil_api_pb2'
  # @@protoc_insertion_point(class_scope:magcilapi.MagCilReply)
  })
_sym_db.RegisterMessage(MagCilReply)

Preds_per_file = _reflection.GeneratedProtocolMessageType('Preds_per_file', (_message.Message,), {
  'DESCRIPTOR' : _PREDS_PER_FILE,
  '__module__' : 'magcil_api_pb2'
  # @@protoc_insertion_point(class_scope:magcilapi.Preds_per_file)
  })
_sym_db.RegisterMessage(Preds_per_file)

Classes_per_model = _reflection.GeneratedProtocolMessageType('Classes_per_model', (_message.Message,), {
  'DESCRIPTOR' : _CLASSES_PER_MODEL,
  '__module__' : 'magcil_api_pb2'
  # @@protoc_insertion_point(class_scope:magcilapi.Classes_per_model)
  })
_sym_db.RegisterMessage(Classes_per_model)



_AUDIOMODELSPREDICT = _descriptor.ServiceDescriptor(
  name='AudioModelsPredict',
  full_name='magcilapi.AudioModelsPredict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=368,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='magcilapi.AudioModelsPredict.Predict',
    index=0,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_MAGCILREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIOMODELSPREDICT)

DESCRIPTOR.services_by_name['AudioModelsPredict'] = _AUDIOMODELSPREDICT

# @@protoc_insertion_point(module_scope)
