# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import magcil_api_pb2 as magcil__api__pb2


class AudioModelsPredictStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.stream_stream(
                '/magcilapi.AudioModelsPredict/Predict',
                request_serializer=magcil__api__pb2.AudioRequest.SerializeToString,
                response_deserializer=magcil__api__pb2.MagCilReply.FromString,
                )


class AudioModelsPredictServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioModelsPredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.stream_stream_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=magcil__api__pb2.AudioRequest.FromString,
                    response_serializer=magcil__api__pb2.MagCilReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magcilapi.AudioModelsPredict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioModelsPredict(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/magcilapi.AudioModelsPredict/Predict',
            magcil__api__pb2.AudioRequest.SerializeToString,
            magcil__api__pb2.MagCilReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
